### ISSUE TITLE
UsePopup option

### ISSUE THREAD

**Issue by serra-caio** [patelmayankce/react-apple-login#8]
Is there a way to enable the usePopup option?

Thanks

**Comment by patelmayankce** [comment]
Sorry right now there is no support of Popup.

**Comment by ohpyupi** [comment]
@patelmayankce With the way the code is implemented, it looks it could entail some code refactoring https://github.com/patelmayankce/react-apple-login/blob/master/src/index.tsx#L50

In order to support the popup option, it needs to use the Javascript SDK provided by Apple. 
https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_js/configuring_your_webpage_for_sign_in_with_apple

**Comment by patelmayankce** [comment]
@ohpyupi ,Sorry for very late reply,
You are right Apple is now supporting popup option.

**Comment by marcin-wicha** [comment]
@patelmayankce 
If you're too busy you can assign it to me :)
I'll add the popup option over the weekend.

**Comment by patelmayankce** [comment]
@marcin-wicha , If you can help anyhow, that would be appreciated.

I already did some code but after successful authentication popup wasn't closed automatically. I will push that code into a new branch and share it with you.

**Comment by muth0mi** [comment]
I kept getting the same issue but found a solution in this thread [Sign in with apple js use popUp](https://developer.apple.com/forums/thread/128788?answerId=408876022#408876022). For popup, the redirect url should be the root domain.

**Comment by patelmayankce** [comment]
Thanks @muth0mi, i will check quickly and release the new version with support of popup.

**Comment by patelmayankce** [comment]
@serra-caio @marcin-wicha @muth0mi 
usePopup option added https://www.npmjs.com/package/react-apple-login/v/1.1.1

Guys thanks for the help.
